# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 07:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('type', models.CharField(choices=[('1', 'male'), ('2', 'female'), ('3', 'kids')], default='1', max_length=1)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='', verbose_name='company photo')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.DateTimeField(verbose_name='from')),
                ('time_to', models.DateTimeField(verbose_name='to')),
                ('invoice', models.FloatField()),
                ('accessories', models.ManyToManyField(to='RentBike.Accessory')),
                ('bikes', models.ManyToManyField(to='RentBike.Bike')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_hour', models.FloatField(default=0, verbose_name='price for an hour (workday)')),
                ('three_hours', models.FloatField(default=0, verbose_name='price for three hours (workday)')),
                ('day', models.FloatField(default=0, verbose_name='price for a day (workday)')),
                ('week', models.FloatField(default=0, verbose_name='price for a week')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='', verbose_name='shop photo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentBike.Company')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentBike.ContactInfo')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='contact_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentBike.ContactInfo'),
        ),
        migrations.AddField(
            model_name='bike',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentBike.Shop'),
        ),
        migrations.AddField(
            model_name='bike',
            name='weekend_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_weekend_prices', to='RentBike.Price'),
        ),
        migrations.AddField(
            model_name='bike',
            name='workday_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_workday_prices', to='RentBike.Price'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentBike.Price'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentBike.Shop'),
        ),
    ]
