# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentBike', '0002_auto_20170919_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_info',
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
